export type Env = {
  SUPABASE_URL: string;
  SUPABASE_SECRET_KEY: string;
  STRAVA_CLIENT_ID: string;
  STRAVA_CLIENT_SECRET: string;
  STRAVA_REDIRECT_URI: string;
  STRAVA_WEBHOOK_VERIFY_TOKEN: string;
  STRAVA_WEBHOOK_SIGNING_SECRET: string;
  STRAVA_WEBHOOK_DISABLE_SIGNATURE_VERIFICATION?: string;
  STRAVA_WEBHOOK_CALLBACK_URL?: string;
  APP_URL: string;
  WORKER_SHARED_SECRET: string;
  STRAVA_SCHEDULED_SYNC_MIN_INTERVAL_HOURS?: string;
  STRAVA_SCHEDULED_SYNC_LIMIT?: string;
};
